import { UserDataFC } from "../interface/interface";

// Sample initial data
export const initialData: UserDataFC[] = [
  {
    id: "1",
    firstname: "Alice",
    lastname: "Johnson",
    age: "28",
    gender: "Female",
    country: "USA",
  },
  {
    id: "2",
    firstname: "Bob",
    lastname: "Brown",
    age: "35",
    gender: "Male",
    country: "Canada",
  },
  {
    id: "3",
    firstname: "Carol",
    lastname: "Davis",
    age: "42",
    gender: "Female",
    country: "UK",
  },
  {
    id: "4",
    firstname: "David",
    lastname: "Smith",
    age: "30",
    gender: "Male",
    country: "Australia",
  },
  {
    id: "5",
    firstname: "Eve",
    lastname: "White",
    age: "23",
    gender: "Other",
    country: "New Zealand",
  },
  {
    id: "6",
    firstname: "Frank",
    lastname: "Clark",
    age: "39",
    gender: "Male",
    country: "Ireland",
  },
  {
    id: "7",
    firstname: "Grace",
    lastname: "Hall",
    age: "31",
    gender: "Female",
    country: "South Africa",
  },
  {
    id: "8",
    firstname: "Henry",
    lastname: "Lee",
    age: "45",
    gender: "Male",
    country: "Singapore",
  },
  {
    id: "9",
    firstname: "Ivy",
    lastname: "Lewis",
    age: "26",
    gender: "Female",
    country: "India",
  },
  {
    id: "10",
    firstname: "Jack",
    lastname: "Walker",
    age: "50",
    gender: "Other",
    country: "Brazil",
  },
];
